id: P006704
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 12:17:57.935353
source_metadata:
  id: bdr:W00KG03809
  title: རྨ་ལྷོའི་དེབ་ཐེར།
  author: ''
  volumes:
    221a5f6bd9ef47308c477101f1408570:
      image_group_id: I1PD90075
      title: ''
      volume_number: 1
      total_pages: 852
      base_file: v001.txt
    ac779c072e7745d897c5143497d06f80:
      image_group_id: I1PD90076
      title: ''
      volume_number: 2
      total_pages: 890
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
